#!/bin/sh -
#
# build script for 1.6
#
# If it's given a buildname it creates a subdirectory and places a build in it,
# otherwise it just creates the docs and class files.
#

JDKPATH=/opt/jdk1.6.0   # JDK 1.6 location
JAVA_MAIL_HOME=/opt/javamail-1.3.1
JAVA_ACTIVATION_HOME=/opt/jaf-1.0.2
JUNIT_HOME=/opt/junit3.8.1

JAVA_HOME=$JDKPATH
export JAVA_HOME

PATH=$JDKPATH/bin:$PATH
export PATH

CLASSPATH=$JAVA_MAIL_HOME/mail.jar:$JAVA_ACTIVATION_HOME/activation.jar:$JUNIT_HOME/junit.jar:$CLASSPATH
export CLASSPATH

if [ "$1" = "test" ]
then
    ant -f jdk16.xml test
else
    if ant -f jdk16.xml build-provider
    then
        ant -f jdk16.xml build
        ant -f jdk16.xml zip-src
    fi
fi

